name: Create a pull request for release.

on:
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # release->masterへのPRが作成されている場合消す
      - name: Delete release pr
        run: |
          gh pr list --state open --base "release" | awk -F' ' '{print $2}'
          gh pr list --state open --base "release" | awk -F' ' '{print $1}'

          base_branch=`gh pr list --state open --base "release" | awk -F' ' '{print $2}'`
          number=`gh pr list --state open --base "release" | awk -F' ' '{print $1}'`
          
          echo "releaseから出ているリスト一覧"
          echo ${base_branch[@]}
          echo "---要素数---"
          echo ${#base_branch[@]}
          echo "---変数値２　たぶん要素番号---"
          echo ${!base_branch[@]}
          
          echo "以下ループ"
          
          for i in ${!base_branch[@]}; do
            echo "${base_branch[$i]}"
            echo "${number[$i]}"
            if [ ${base_branch[$i]} = "release->masterへのマージ" ]; then
              echo "closeするぞい"
              gh pr close "${number[$i]}"
            fi
          done

      # リリース用PRを作成
      - name: Create release pr
        run: |
          gh pr create -B main -t "release->masterへのマージ" -b ""
          
