name: Create release tag after merge release_branch

on:
  push:
    branches: [ release ]

jobs:
  create_release_tag:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      TZ: 'Asia/Tokyo'

      steps:
        - uses: actions/checkout@v1

          # タグを生成「YYYY.MM.DD.(当日リリース回数)」
        - name: Generate release tag
          id: release_tag
          run: |
            today=$(date+'%Y.%m.%d')
            echo "::set-output name=release_tag::v3.$today.1"

        # 前回リリースからの差分をもとに、リリースノートの本文を生成する
        - name: Generate release note
          id: release_note
          run: |
            echo "::set-output name=release_note::none"

        # タグを切り、リリースノートを作成する
        - name: Create Release
          run: |
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{ \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\"}" \
              https://api.github.com/repos/${{ github.repository }}/releases



