name: Create release tag after merge release_branch

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Current Date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +'%Y%m%d')"

        # Gitを使用するための設定
      - name: Git Settings
        run: | 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      # 同日リリースの場合.1を変更するため、すでにタグがあるか確認する
      # git tagでリモートの最新タグを１つ取得　比較して一致する場合末尾の数字を１つ加算⇨どうよ？
      # v3のところも前回の値をそのまま使うという作戦　いいと思います。　そうすればｖ４にする時も一回だけ手動でつくればいいの。

      # タグの作成・反映
      - name: Generate tag
        run: |
          git tag -a -m "Test" "v3.$(date +'%Y%m%d').1"
          git tag

      # タグのコミット
      - name: Push Release tag
        run: |
          git push origin --tags

      # リリースタグの作成
      - name: Generate Release Tag
        uses: softprops/action-gh-release@v1
        with:
          name: "${{env.CURRENT_DATETIME}}リリース"
          tag_name: "v3.${{env.TAG_NAME}}.1"
          generate_release_notes: true