name: Create release tag after merge release_branch

on:
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Current Date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        id: env
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

        # Gitを使用するための設定
      - name: Git Settings
        run: | 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Create Tag Name
        run: |
          today=$(date +'%Y%m%d')
          echo "RELEASE_TAG=$v3.$today.1" >> $GITHUB_ENV
          RELEASE_NOTE="リリースノート本文"
          echo "RELEASE_NOTE=$RELEASE_NOTE" >> $GITHUB_ENV

      # タグを切り、リリースノートを作成する
      - name: Create Release Tag
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${RELEASE_TAG}\", \"name\": \"${TAG_NAME}リリース\", \"body\": \"${RELEASE_NOTE}\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases


