name: Create release tag after merge release_branch

on:
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Current Date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      # タグの作成・反映
      - name: Generate tag
        run: |
          git config --global user.name "GitHub Action"       # push時に使われるgitユーザ名（表示名）
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git tag "v.$(date +'%Y%m%d').1"
          git push origin "v.$(date +'%Y%m%d').1"

      - name: Generate Release Tag
        uses: softprops/action-gh-release@v1
        with:
          name: "${{env.CURRENT_DATETIME}}リリース"
          tag_name: "v.${{env.CURRENT_DATETIME}}.1"
          generate_release_notes: true
