name: Create release tag after merge release_branch

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Current Date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

        # Gitを使用するための設定
      - name: Git Settings
        run: | 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://github.com/Yusuke-Nara-0321/github_actions_inspection.git"
          git remote -v
          ssh -T git@github.com

      # タグの作成・反映
      - name: Generate tag
        run: |
          git tag "v.$(date +'%Y%m%d').1"
          git push origin "v.$(date +'%Y%m%d').1"

      - name: Generate Release Tag
        uses: softprops/action-gh-release@v1
        with:
          name: "${{env.CURRENT_DATETIME}}リリース"
          tag_name: "v.${{env.CURRENT_DATETIME}}.1"
          generate_release_notes: true