name: Create release tag after merge release_branch

on:
  push:
    branches:
      - release
    types:
      - closed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Current Date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Generate Release Tag
        uses: softprops/action-gh-release@v1
        with:
          name: "${{env.CURRENT_DATETIME}}リリース"
          tag_name: "v.${{env.CURRENT_DATETIME}}.1"
          generate_release_note: true
